service: lambdabistros
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  register-client:
    handler: ./src/functions/register-client/index.handler
    environment:
      AWS_ACCESS_KEY_ID: ${env:REGISTER_CLIENT_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${env:REGISTER_CLIENT_AWS_SECRET_ACCESS_KEY}
      APIGATEWAY_ENDPOINT: ${env:REGISTER_CLIENT_APIGATEWAY_ENDPOINT}
      MONGODB_URI: ${env:REGISTER_CLIENT_MONGODB_URI}
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  get-dishes:
    handler: ./src/functions/get-dishes/index.handler
    events:
      - http:
          path: /dishes
          method: get